server:
  port: 8084

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification_service

api:
  key: "super-secret-api-key-notification-service"
