version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: blood_donation_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - blood_donation_net

  api-gateway:
    build: ./api-gateway
    container_name: api_gateway_service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/gateway_db
      - DONOR_SERVICE_URL=http://donor-service:8081
      - INVENTORY_SERVICE_URL=http://inventory-service:8082
      - REQUEST_SERVICE_URL=http://request-service:8083
      - NOTIFICATION_SERVICE_URL=http://notification-service:8084
    depends_on:
      - mongodb
    networks:
      - blood_donation_net

  donor-service:
    build: ./donor-service
    container_name: donor_service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/donor_db
    depends_on:
      - mongodb
    networks:
      - blood_donation_net

  inventory-service:
    build: ./inventory-service
    container_name: inventory_service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/inventory_db
    depends_on:
      - mongodb
    networks:
      - blood_donation_net

  request-service:
    build: ./request-service
    container_name: request_service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/request_db
      - DONOR_SERVICE_URL=http://donor-service:8081
    depends_on:
      - mongodb
    networks:
      - blood_donation_net

  notification-service:
    build: ./notification-service
    container_name: notification_service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/notification_db
    depends_on:
      - mongodb
    networks:
      - blood_donation_net

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "5173:5173"
    networks:
      - blood_donation_net

volumes:
  mongo_data:

networks:
  blood_donation_net:
    driver: bridge
