server:
  port: 8080

spring:
  application:
    name: gateway-service

# JWT OAuth 2.0 Configuration
jwt:
  secret: BloodDonationSuperSecretKeyForJWTTokenGeneration2026!
  expiration-ms: 86400000 # 24 Hours

# OpenAPI / Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Security & Gateway Rate Limiting Configuration
gateway:
  security:
    api-key-header: X-API-KEY
    api-key-secret: blood_donation_secret_key_2026
  rate-limit:
    requests-per-minute: 60

