server:
  port: 8081

spring:
  application:
    name: donor-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/donor_service

api:
  key: ${API_SECURITY_KEY:blood_donation_secret_key_2026}
  security:
    key: ${API_SECURITY_KEY:blood_donation_secret_key_2026}
