server:
  port: 8083

spring:
  application:
    name: request-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/request_service

api:
  key: ${API_SECURITY_KEY:blood_donation_secret_key_2026}
  security:
    key: ${API_SECURITY_KEY:blood_donation_secret_key_2026}

donor-service:
  url: ${DONOR_SERVICE_URL:http://localhost:8081}
