version: '3.8'

services:
  inventory-db:
    image: mongo:latest
    container_name: inventory_db
    ports:
      - "27018:27017"
    volumes:
      - inventory_db_data:/data/db

  inventory-service:
    build: .
    container_name: inventory_service
    ports:
      - "8083:8083"
    environment:
      - MONGO_URI=mongodb://inventory-db:27017/inventory_db
      - API_KEY=${API_KEY:-blood_donation_secret_key_2026}
    depends_on:
      - inventory-db

volumes:
  inventory_db_data:
